// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Webapi__Dom__Element = require("bs-webapi/src/Webapi/Webapi__Dom/Webapi__Dom__Element.js");
var Webapi__Dom__Document = require("bs-webapi/src/Webapi/Webapi__Dom/Webapi__Dom__Document.js");

var bodyElement = Belt_Option.getExn(Belt_Option.flatMap(Belt_Option.flatMap(Webapi__Dom__Document.asHtmlDocument(document), (function (prim) {
                return Caml_option.nullable_to_opt(prim.body);
              })), Webapi__Dom__Element.asHtmlElement));

bodyElement.style.setProperty("border", "5px solid red", "");

exports.bodyElement = bodyElement;
/* bodyElement Not a pure module */
